name: Deploy Resources

on:
  workflow_dispatch:

env:
  prefix: wtht10

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - webappdev
          - webapptest
          - webappprod
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./ARM-Templates/container-webapp-template.json
        parameters: webAppName=${{ env.prefix }}${{ matrix.app }}