name: Challenge 4

on:
  workflow_dispatch:
  issues:
    types: opened
    
jobs:
  job1:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    - name: Hello
      shell: pwsh
      run: |
        Write-Host "Hello World"
      

    # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
    # - name: 'Login via Azure CLI'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

  job2:
    needs: job1
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'red'
